/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Articles {
  author: string;
  content: Generated<string | null>;
  created_at: Generated<Date | null>;
  id: Generated<number>;
  title: string;
  updated_at: Generated<Date | null>;
}

export interface DB {
  articles: Articles;
}
